name: daily-trend-search
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  search-trends:
    runs-on: ubuntu-latest
    steps:
    - name: Search trends and send to slack
      run: echo "Trend search completed!"
